#!/bin/bash
set -e

# Usage
# =====
# ./runmain server main
#

Usage="<<< $0 MODULE_NAME MODULE_FUNCTION >>>"

Module="${1:?${Usage}}"
Function="${2:-main}"

python -m "${Module}.${Function}"

# Why? Because otherwise:
#
#     Traceback (most recent call last):
#       File "./sources/server.py", line 4, in <module>
#         from .xdotool import *
#     ValueError: Attempted relative import in non-package
#
# 